import { CategoryPalette } from '@/constants/theme';

/** Canonical buckets for market prediction (supermarket + Kmart + tech). */
export const MARKET_CATEGORIES = [
  'Dairy',
  'Meat & deli',
  'Produce',
  'Bakery',
  'Frozen',
  'Drinks',
  'Snacks',
  'Pantry',
  'Cleaning',
  'Personal care',
  'Pet',
  'Baby',
  'Technology',
  'Home & kitchen',
  'Clothing',
  'Stationery',
  'Toys & games',
  'Sports & outdoors',
  'Storage',
  'Other',
] as const;

export type MarketCategory = (typeof MARKET_CATEGORIES)[number];

const RULES: Array<{ category: MarketCategory; words: string[] }> = [
  {
    category: 'Technology',
    words: [
      'usb',
      'hdmi',
      'sd card',
      'micro sd',
      'memory card',
      'flash drive',
      'hard drive',
      'ssd',
      'laptop',
      'chromebook',
      'tablet',
      'ipad',
      'iphone',
      'android',
      'phone case',
      'phone cover',
      'screen protector',
      'charger',
      'charging',
      'power bank',
      'cable',
      'earbud',
      'earphone',
      'headphone',
      'headset',
      'bluetooth',
      'speaker',
      'webcam',
      'keyboard',
      'mouse',
      'monitor',
      ' tv',
      'television',
      'smartwatch',
      'smart watch',
      'fitbit',
      'router',
      'modem',
      'wifi',
      'wi-fi',
      'printer',
      'ink cartridge',
      'toner',
      'camera',
      'gopro',
      'drone',
      'gaming',
      'playstation',
      'xbox',
      'nintendo',
      'nintendo switch',
      'controller',
      'console',
      'adapter',
      'dongle',
      'extension cord',
      'powerboard',
      'power board',
      'led strip',
      'smart bulb',
      'smart light',
      'alexa',
      'google home',
      'chromecast',
      'fire stick',
      'tech',
      'electronic',
    ],
  },
  {
    category: 'Home & kitchen',
    words: [
      'kettle',
      'toaster',
      'blender',
      'mixer',
      'air fryer',
      'microwave',
      'frypan',
      'saucepan',
      'frying pan',
      'bakeware',
      'baking tray',
      'cutting board',
      'chopping board',
      'utensil',
      'cutlery',
      'knife set',
      'plate',
      'bowl',
      'mug',
      'tumbler',
      'container set',
      'food container',
      'lunch box',
      'thermos',
      'drink bottle',
      'water bottle',
      'pillow',
      'duvet',
      'quilt',
      'sheet set',
      'bedsheet',
      'towel',
      'bath mat',
      'shower curtain',
      'curtain',
      'rug',
      'doormat',
      'candle',
      'diffuser',
      'vase',
      'photo frame',
      'lamp',
      'light bulb',
      'heater',
      'ironing',
      'vacuum',
      'mop',
      'broom',
      'dustpan',
      'laundry basket',
      'hangers',
      'clothes hanger',
      'kitchen',
      'cookware',
      'crockery',
      'dinnerware',
    ],
  },
  {
    category: 'Clothing',
    words: [
      'sock',
      'socks',
      't-shirt',
      'shirt',
      'jumper',
      'hoodie',
      'jacket',
      'coat',
      'jeans',
      'pants',
      'shorts',
      'skirt',
      'dress',
      'underwear',
      'brief',
      'legging',
      'pyjama',
      'pajama',
      'slippers',
      'shoes',
      'sneakers',
      'sandals',
      'boots',
      'beanie',
      'scarf',
      'gloves',
      'belt',
      'wallet',
      'handbag',
      'backpack',
      'tote',
      'clothing',
      'apparel',
      'fashion',
    ],
  },
  {
    category: 'Stationery',
    words: [
      ' pen ',
      ' pens ',
      'pencil',
      'marker',
      'highlighter',
      'notebook',
      'notepad',
      'sticky note',
      'post-it',
      'folder',
      'binder',
      'stapler',
      'staple',
      'paperclip',
      'scissors',
      ' sticky tape',
      'packing tape',
      'glue',
      'ruler',
      'eraser',
      'sharpener',
      'a4 paper',
      'copy paper',
      'envelope',
      'diary',
      'planner',
      'stationery',
      'office',
    ],
  },
  {
    category: 'Toys & games',
    words: [
      'toy',
      'lego',
      'doll',
      'barbie',
      'action figure',
      'puzzle',
      'board game',
      'card game',
      'plush',
      'teddy',
      'soft toy',
      'playset',
      'hot wheels',
      'nerf',
      'slime',
      'colouring',
      'coloring',
      'crayon',
      'playdough',
      'play-doh',
    ],
  },
  {
    category: 'Sports & outdoors',
    words: [
      'yoga',
      'dumbbell',
      'kettlebell',
      'resistance band',
      'fitness',
      'gym',
      'sports',
      'football',
      'soccer',
      'basketball',
      'tennis',
      'cricket',
      'golf',
      'bike',
      'bicycle',
      'helmet',
      'camping',
      'tent',
      'sleeping bag',
      'esky',
      'cooler',
      'bbq',
      'barbecue',
      'fishing',
      'outdoor',
      'swim',
      'goggles',
    ],
  },
  {
    category: 'Storage',
    words: [
      'storage box',
      'storage bin',
      'storage tote',
      'organiser',
      'organizer',
      'drawer unit',
      'shelf',
      'shelving',
      'crate',
      'basket',
      'tub ',
      'zip lock',
      'ziplock',
      'vacuum bag',
      'wardrobe',
      'cube storage',
    ],
  },
  {
    category: 'Dairy',
    words: [
      'milk',
      'yoghurt',
      'yogurt',
      'cheese',
      'butter',
      'cream',
      'dairy',
      'custard',
      'lactose',
    ],
  },
  {
    category: 'Meat & deli',
    words: [
      'chicken',
      'beef',
      'pork',
      'lamb',
      'bacon',
      'ham',
      'salami',
      'sausage',
      'mince',
      'steak',
      'turkey',
      'deli',
      'meat',
    ],
  },
  {
    category: 'Produce',
    words: [
      'banana',
      'apple',
      'orange',
      'lettuce',
      'tomato',
      'potato',
      'onion',
      'avocado',
      'broccoli',
      'carrot',
      'fruit',
      'veg',
      'salad',
      'grape',
      'berry',
      'spinach',
    ],
  },
  {
    category: 'Bakery',
    words: ['bread', 'bun', 'bagel', 'croissant', 'muffin', 'bakery', 'wrap', 'tortilla', 'pita'],
  },
  {
    category: 'Frozen',
    words: ['frozen', 'ice cream', 'icecream', 'mccain', 'fries', 'nugget', 'pizza'],
  },
  {
    category: 'Drinks',
    words: [
      'juice',
      'cola',
      'soft drink',
      'water',
      'coffee',
      'tea',
      'beer',
      'wine',
      'cordial',
      'soda',
      'energy drink',
    ],
  },
  {
    category: 'Snacks',
    words: [
      'chip',
      'crisp',
      'cookie',
      'biscuit',
      'chocolate',
      'lolly',
      'candy',
      'snack',
      'cracker',
      'popcorn',
      'protein bar',
      'muesli bar',
    ],
  },
  {
    category: 'Cleaning',
    words: [
      'bleach',
      'detergent',
      'dishwasher',
      'laundry',
      'cleaner',
      'disinfectant',
      'wipes',
      'sponge',
      'bin liner',
      'garbage',
      'toilet paper',
      'tissue',
      'paper towel',
      'fabric softener',
      'ajax',
      'domestos',
      'surf',
      'omo',
    ],
  },
  {
    category: 'Personal care',
    words: [
      'shampoo',
      'conditioner',
      'soap',
      'body wash',
      'toothpaste',
      'toothbrush',
      'deodorant',
      'razor',
      'tampon',
      'sanitary',
      'lotion',
      'skincare',
      'moisturizer',
      'sunscreen',
      'floss',
      'mouthwash',
      'hygiene',
      'nivea',
      'dove',
      'colgate',
      'makeup',
      'mascara',
      'lipstick',
      'nail polish',
      'perfume',
      'cologne',
    ],
  },
  {
    category: 'Pet',
    words: ['dog', 'cat', 'pet', 'puppy', 'kitten', 'litter', 'whiskas', 'pedigree'],
  },
  {
    category: 'Baby',
    words: ['nappy', 'nappies', 'diaper', 'baby', 'formula', 'wipes baby', 'infant'],
  },
  {
    category: 'Pantry',
    words: [
      'rice',
      'pasta',
      'cereal',
      'flour',
      'sugar',
      'salt',
      'oil',
      'sauce',
      'spice',
      'canned',
      'tinned',
      'beans',
      'oat',
      'jam',
      'honey',
      'peanut butter',
    ],
  },
];

const GUESS_ALIASES: Record<string, MarketCategory> = {
  dairy: 'Dairy',
  milk: 'Dairy',
  groceries: 'Pantry',
  grocery: 'Pantry',
  food: 'Pantry',
  meat: 'Meat & deli',
  deli: 'Meat & deli',
  produce: 'Produce',
  fruit: 'Produce',
  vegetable: 'Produce',
  vegetables: 'Produce',
  bakery: 'Bakery',
  bread: 'Bakery',
  frozen: 'Frozen',
  drinks: 'Drinks',
  beverage: 'Drinks',
  beverages: 'Drinks',
  snacks: 'Snacks',
  snack: 'Snacks',
  sweets: 'Snacks',
  pantry: 'Pantry',
  cleaning: 'Cleaning',
  household: 'Home & kitchen',
  laundry: 'Cleaning',
  hygiene: 'Personal care',
  'personal care': 'Personal care',
  toiletries: 'Personal care',
  beauty: 'Personal care',
  pet: 'Pet',
  baby: 'Baby',
  tech: 'Technology',
  technology: 'Technology',
  electronics: 'Technology',
  electronic: 'Technology',
  gadgets: 'Technology',
  computer: 'Technology',
  phone: 'Technology',
  home: 'Home & kitchen',
  kitchen: 'Home & kitchen',
  housewares: 'Home & kitchen',
  furniture: 'Home & kitchen',
  clothing: 'Clothing',
  apparel: 'Clothing',
  fashion: 'Clothing',
  clothes: 'Clothing',
  stationery: 'Stationery',
  office: 'Stationery',
  school: 'Stationery',
  toys: 'Toys & games',
  toy: 'Toys & games',
  games: 'Toys & games',
  sports: 'Sports & outdoors',
  outdoor: 'Sports & outdoors',
  fitness: 'Sports & outdoors',
  storage: 'Storage',
  organisation: 'Storage',
  organization: 'Storage',
  kmart: 'Home & kitchen',
  other: 'Other',
};

export function categorizeProduct(name: string, categoryGuess = ''): MarketCategory {
  const guess = categoryGuess.toLowerCase().trim();
  if (guess) {
    const direct = GUESS_ALIASES[guess];
    if (direct) return direct;
    for (const [key, cat] of Object.entries(GUESS_ALIASES)) {
      if (guess.includes(key)) return cat;
    }
    for (const cat of MARKET_CATEGORIES) {
      if (guess.includes(cat.toLowerCase())) return cat;
    }
  }

  const n = ` ${name.toLowerCase()} `;
  for (const rule of RULES) {
    if (rule.words.some((w) => n.includes(w))) return rule.category;
  }
  return 'Other';
}

export function marketCategoryColor(category: MarketCategory, index = 0): string {
  const i = MARKET_CATEGORIES.indexOf(category);
  return CategoryPalette[(i >= 0 ? i : index) % CategoryPalette.length];
}
